### PR TITLE
FIRST JAVASKRIPT TASK

### PR DESCRIPTION
**Pull request by VladChudin**

### CODE REVIEW

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Make sure to push your solution to the GH https://mate-academy.github.io/layout_task-guideline/#codenpm-startcode-to-open-the-page

**Comment by VladChudin** [comment]
> Make sure to push your solution to the GH https://mate-academy.github.io/layout_task-guideline/#codenpm-startcode-to-open-the-page

https://github.com/mate-academy/js_task-transportation-on-vacation/pull/4688 i have a problem with commit please check my pull request on this link

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Hi, you don't need to create a new PR, if you need help feel free in the fe_chat

**Comment by VladChudin** [comment]
> Hi, you don't need to create a new PR, if you need help feel free in the fe_chat

i now but i don't want to fix it please check new PR.

**Review by vadiimvooo — CHANGES_REQUESTED** [review]
Good job, but you have to fix this PR by pushing your solution, if you need help feel free in the fe_chat.

**Pull request closed without merging**
