### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by basiak89**

### CODE REVIEW

**Comment by VadimMentorQA** [comment]
reopen comment

**Review by VadimMentorQA — COMMENTED** [review]
.

**Comment by basiak89** [comment]
reopened

**Comment by VadimMentorQA** [comment]
@basiak89 Try to add a commit and push your changes - let's see the PR status.

**Comment by basiak89** [comment]
all changes already have been made but could not reopen solution 3340

**Comment by VadimMentorQA** [comment]
@basiak89 Commit and push your local changes into the current branch.

**Comment by basiak89** [comment]
i think it should be done

**Comment by basiak89** [comment]
it says now nothing to commit

**Comment by VadimMentorQA** [comment]
@basiak89 Make a minor change (variable name, the test name), commit it, and push it to Github

**Comment by basiak89** [comment]
please could you check it should work

**Comment by VadimMentorQA** [comment]
@basiak89 Still doesn't work. Looks like this branch has conflicts that must be resolved. Fix it, and tag me here, and ask mentors in the chat about the status.

**Comment by basiak89** [comment]
done :)

**Comment by basiak89** [comment]
@VadimMentorQA  I am not sure what kind of problem it is. Please could you support? All test have been passed in Visual code.
image_720 (1)](https://github.com/mate-academy/js_task-transportation-on-vacation/assets/145010260/695c238d-3075-4f49-8144-aff7047d67ed)
m/mate-academy/js_task-transportation-on-vacation/assets/145010260/80932ea9-f09f-4da2-94a6-dd6b3e6cc057)

**Comment by basiak89** [comment]
@VadimMentorQA All test have been passed in Visual code
image (9)

**Comment by basiak89** [comment]
@VadimMentorQA All tests have been passed in Visual code.
image_720 (1)

**Pull request closed without merging**
